apiVersion: v1
kind: Service
metadata:
  name: backend-counter-go-grpc-nextjs-postgres
  namespace: counter-go-grpc-nextjs-postgres
spec:
  selector:
    app: backend-counter-go-grpc-nextjs-postgres
  ports:
    - protocol: TCP
      name: http-port
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: grpc-port
      port: 9090
      targetPort: 9090
