apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-counter-python-nextjs-postgres
  namespace: counter-python-nextjs-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-counter-python-nextjs-postgres
  template:
    metadata:
      labels:
        app: backend-counter-python-nextjs-postgres
    spec:
      containers:
        - name: backend-counter-python-nextjs-postgres
          image: image:tag
          envFrom:
            - configMapRef:
                name: config-backend-counter-python-nextjs-postgres
            - secretRef:
                name: secret-backend-counter-python-nextjs-postgres
